### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by dersuchendee** [rkeytech/goodreads-editions#5]
I'm trying to find editions based on a list of books I have. Some may not have edition/any entry on Goodreads.
Running the code I get:
```
Traceback (most recent call last):
  File "C:/Users/mm/PycharmProjects/fff/findisbn.py", line 119, in <module>
    ed_details = get_editions_details(isbn)
  File "C:/Users/mm/PycharmProjects/fff/findisbn.py", line 67, in get_editions_details
    ed_item = soup.find("div", class_="otherEditionsLink").find("a")
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by rkeytech** [comment]
@dersuchendee Goodreads changed the way they display the editions and how you can find them in the source code. Probably the error caused by an item which didn't have any editions about that language. I don't think I'll take a look at it soon since I'm very busy with other projects. I've put the issue as a good first issue, since it doesn't seem to be something serious, and maybe someone else will solve it.
